Fix tag creation. (#5)

diff --git a/.github/workflows/release.yml b/.github/workflows/release.yml
--- a/.github/workflows/release.yml
+++ b/.github/workflows/release.yml
@@ -26,13 +26,25 @@ jobs:
           repository: ${{ github.repository }}
           prefix: v
 
-      - name: Retrieve Version from `build.gradle`
+      - name: Retrieve Version from Gradle
         id: retrieve_version
-        run: echo "VERSION=$(./gradlew -q properties | grep "^version:" | awk '{print $2}')" >> $GITHUB_ENV
+        run: |
+          VERSION=$(./gradlew -q printVersion)
+          if [[ -z "$VERSION" ]]; then
+            echo "Error: Version extraction failed!" >&2
+            exit 1
+          fi
+          echo "VERSION=$VERSION" >> $GITHUB_OUTPUT
 
       - name: Resolve New Tag Name
         id: resolve_new_tag_name
-        run: echo "tag=v${{ env.version }}" >> $GITHUB_ENV
+        run: |
+          echo "tag=v${{ steps.retrieve_version.outputs.VERSION }}" >> $GITHUB_OUTPUT
+
+      - name: Print Version information
+        run: |
+          echo "Extracted Version: ${{ steps.retrieve_version.outputs.VERSION }}"
+          echo "Resolved Tag: ${{ steps.resolve_new_tag_name.outputs.tag }}"
 
       - name: Import GPG Key
         run: |
@@ -40,7 +52,7 @@ jobs:
           echo "${{ secrets.SIGNING_PASSWORD }}" | gpg --batch --yes --pinentry-mode loopback --passphrase-fd 0 --export-secret-keys > /tmp/secret.gpg
 
       - name: Release to Sonatype
-        if: ${{ steps.previoustag.outputs.tag != env.tag }}
+        if: ${{ steps.previoustag.outputs.tag != steps.resolve_new_tag_name.outputs }}
         run: |
           ./gradlew publishToSonatype closeAndReleaseSonatypeStagingRepository --no-daemon \
             -Psigning.keyId=${{ secrets.SIGNING_KEY_ID }} \
@@ -51,9 +63,9 @@ jobs:
           ORG_GRADLE_PROJECT_sonatypePassword: ${{ secrets.SONATYPE_PASSWORD }}
 
       - name: Create Tag
-        if: ${{ steps.previoustag.outputs.tag != env.tag }}
+        if: ${{ steps.previoustag.outputs.tag != steps.resolve_new_tag_name.outputs.tag }}
         uses: negz/create-tag@v1
         with:
-          version: ${{ env.tag }}
-          message: Release ${{ env.tag }}
+          version: ${{ steps.resolve_new_tag_name.outputs.tag }}
+          message: Release ${{ steps.resolve_new_tag_name.outputs.tag }}
           token: ${{ secrets.GITHUB_TOKEN }}
